version: '3.8'
services:

#  db:
#    image: postgres


  elasticsearch:
    image: elasticsearch:7.16.3
    depends_on:
      - db
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
