spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db_news_comments
    username: postgres
    password: postgres
  liquibase:
    contexts: test
  jpa:
    properties:
      hibernate:
        search:
          backend:
            type: elasticsearch
            hosts: localhost:9200
#cache:
#  algorithm: LRU
#  capacity: 50
