spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_comments
    username: postgres
    password: postgres

  liquibase:
    contexts: prod

  jpa:
    properties:
      hibernate:
        search:
          backend:
            type: elasticsearch
            hosts: localhost:9200
#cache:
#  algorithm: LRU
#  capacity: 50

map:
  value: localhost

